samplenames = { 'dileptonM' : 'Z Mass (GeV)',
                'h_cutflow' : 'Cutflow',
                'h_recoil'  : 'Recoil (GeV)',
                'dileptonPt' : 'Z P_{T} (GeV)',
                'nJets'     : 'Number of Jets',
                'j1pT'      : 'Leading Jet P_{T} (GeV)',
                'LeptonPt'  : 'Leading Lepton P_{T}',
                'LeptonEta' : 'Leading Lepton #eta',
                'j1etaWidth' : 'Leading Jet #eta Width',
                'LeptonPhi' : 'Leading Lepton #phi',
                'j1PF12PtFrac_ID_1' : 'P^{12}_{T} Fraction',
                'j1PFPtFrac_ID_2' : 'P^{123}_{T} Fraction',
                'subleadingLeptonPt' : 'Trailing Lepton P_{T} (GeV)',
                'subleadingLeptonEta' : 'Trailing Lepton #eta',
                'subleadingLeptonPhi' : 'Trailing Lepton #phi',
                'nVtx' : 'Number of Primary Vertices',
                'EcalPtUnc' : 'Photon P_{T} (GeV)',
                'HcalptUnc' : 'Neutral Hadron P_{T} (GeV)',
                'TrackerPtUnc' : 'Charged Hadron P_{T} (GeV)',
                'PF123PtFraction' : 'P_{T}^{123} Fraction',
                'j1Eta' : 'Leading Jet #eta',
                'j1Phi' : 'Leading Jet #phi',
                'pfMET' : 'E_{T}^{miss} (GeV)',
                'LeptonEtaPhiComp' : {'x':'Leading Lepton #eta', 'y':'Leading Lepton #phi'},
                'leadingLeptonEtaPhiComp' : {'x':'Leading Lepton #eta', 'y':'Leading Lepton #phi'},
                'subleadingLeptonEtaPhiComp' : {'x':'Subleading Lepton #eta', 'y':'Subleading Lepton #phi'},
                'j1EtaPhiComp' : {'x':'Leading Jet #eta', 'y':'Leading Jet #phi'},
                'dileptonPt' : 'Z P_{T} (GeV)',
                'dileptonM' : 'Z Mass (GeV)'
        

}
